name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # Ensure the workflow can push changes

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full repo history

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/snake.svg  # Fixed incorrect 'outputs' key

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --unshallow  # Ensure full repo history
          git checkout main
          git add -A
          git commit -m "🐍 Update GitHub contribution snake animation" || echo "No changes to commit"
          git push
